# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tp3_grpc/scoring.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tp3_grpc/scoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16tp3_grpc/scoring.proto\x12\x06\x61rrest\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe1\x01\n\x0b\x43rimeReport\x12\x0c\n\x04iucr\x18\x01 \x01(\t\x12\x14\n\x0cprimary_type\x18\x02 \x01(\t\x12!\n\x14location_description\x18\x03 \x01(\tH\x00\x88\x01\x01\x12(\n\x04\x64\x61te\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\x08latitude\x18\x05 \x01(\x01H\x01\x88\x01\x01\x12\x16\n\tlongitude\x18\x06 \x01(\x01H\x02\x88\x01\x01\x42\x17\n\x15_location_descriptionB\x0b\n\t_latitudeB\x0c\n\n_longitude\"0\n\nCrimeBatch\x12\"\n\x05items\x18\x01 \x03(\x0b\x32\x13.arrest.CrimeReport\"\\\n\nPrediction\x12\x0e\n\x06\x61rrest\x18\x01 \x01(\x05\x12\x13\n\x0bprobability\x18\x02 \x01(\x01\x12\x12\n\nmodel_name\x18\x03 \x01(\t\x12\x15\n\rmodel_version\x18\x04 \x01(\x05\x32~\n\rArrestScoring\x12\x32\n\x07Predict\x12\x13.arrest.CrimeReport\x1a\x12.arrest.Prediction\x12\x39\n\rPredictStream\x12\x12.arrest.CrimeBatch\x1a\x12.arrest.Prediction0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tp3_grpc.scoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CRIMEREPORT']._serialized_start=68
  _globals['_CRIMEREPORT']._serialized_end=293
  _globals['_CRIMEBATCH']._serialized_start=295
  _globals['_CRIMEBATCH']._serialized_end=343
  _globals['_PREDICTION']._serialized_start=345
  _globals['_PREDICTION']._serialized_end=437
  _globals['_ARRESTSCORING']._serialized_start=439
  _globals['_ARRESTSCORING']._serialized_end=565
# @@protoc_insertion_point(module_scope)
