# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tp3_grpc import scoring_pb2 as tp3__grpc_dot_scoring__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tp3_grpc/scoring_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArrestScoringStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/arrest.ArrestScoring/Predict',
                request_serializer=tp3__grpc_dot_scoring__pb2.CrimeReport.SerializeToString,
                response_deserializer=tp3__grpc_dot_scoring__pb2.Prediction.FromString,
                _registered_method=True)
        self.PredictStream = channel.unary_stream(
                '/arrest.ArrestScoring/PredictStream',
                request_serializer=tp3__grpc_dot_scoring__pb2.CrimeBatch.SerializeToString,
                response_deserializer=tp3__grpc_dot_scoring__pb2.Prediction.FromString,
                _registered_method=True)


class ArrestScoringServicer:
    """Missing associated documentation comment in .proto file."""

    def Predict(self, request, context):
        """Unary: un reporte, una predicción.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictStream(self, request, context):
        """Server streaming: un lote, N predicciones en el mismo orden que los items.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArrestScoringServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=tp3__grpc_dot_scoring__pb2.CrimeReport.FromString,
                    response_serializer=tp3__grpc_dot_scoring__pb2.Prediction.SerializeToString,
            ),
            'PredictStream': grpc.unary_stream_rpc_method_handler(
                    servicer.PredictStream,
                    request_deserializer=tp3__grpc_dot_scoring__pb2.CrimeBatch.FromString,
                    response_serializer=tp3__grpc_dot_scoring__pb2.Prediction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arrest.ArrestScoring', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arrest.ArrestScoring', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArrestScoring:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arrest.ArrestScoring/Predict',
            tp3__grpc_dot_scoring__pb2.CrimeReport.SerializeToString,
            tp3__grpc_dot_scoring__pb2.Prediction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/arrest.ArrestScoring/PredictStream',
            tp3__grpc_dot_scoring__pb2.CrimeBatch.SerializeToString,
            tp3__grpc_dot_scoring__pb2.Prediction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
